package cli

import (
	"fmt"
	"os"
)

// The function is POSIX-compatible so one template serves zsh and bash. A
// child process can't cd its parent shell, so the binary prints the jump
// as a script and this function evals it — the same arrangement as wt's
// wt() function.
const shellFunction = `# wt-ui — generated by "wt-tui init"
wt-ui() {
    local _wt_script
    _wt_script="$(%q "$@")" || return $?
    if [ -n "$_wt_script" ]; then
        _wt_prev="$PWD"
        eval "$_wt_script"
    fi
}
`

func shellInit(args []string) error {
	if len(args) != 1 || (args[0] != "zsh" && args[0] != "bash") {
		return fmt.Errorf("usage: wt-tui init <zsh|bash>")
	}
	bin, err := os.Executable()
	if err != nil {
		return err
	}
	fmt.Fprintf(stdout, shellFunction, bin)
	return nil
}
