package cli

import (
	"fmt"
	"os"
)

// The function is POSIX-compatible apart from its name, which bash and zsh
// both accept. A child process can't cd its parent shell, so the binary
// prints the jump as a script and this function evals it — the same
// arrangement as wt's wt() function. Subcommands whose output is for
// reading, not evaluating, pass straight through. _wt_prev is the per-shell
// variable wt's own `wt switch` toggles on, so a jump made here is one
// `wt switch` can return from.
const shellFunction = `# wt-ui — generated by "wt-ui init"
wt-ui() {
    case "$1" in
        init|help|version|-h|--help|--version)
            %[1]q "$@"
            return $?
            ;;
    esac
    local _wt_script
    _wt_script="$(WT_UI_WRAPPER=1 %[1]q "$@")" || return $?
    if [ -n "$_wt_script" ]; then
        _wt_prev="$PWD"
        eval "$_wt_script"
    fi
}
`

func shellInit(args []string) error {
	if len(args) != 1 || (args[0] != "zsh" && args[0] != "bash") {
		return fmt.Errorf("usage: wt-ui init <zsh|bash>")
	}
	bin, err := os.Executable()
	if err != nil {
		return err
	}
	fmt.Fprintf(stdout, shellFunction, bin)
	return nil
}
